### ISSUE TITLE
failed to start TG client

### ISSUE THREAD

**Issue by nik13513513** [Infactum/tg2sip#12]
Hello!

Tryed to start app, received api_id & api_hash, writed them to settings file, and got this message:

ps. gen_db freezes after enter phone number.

[13:06:35.934][t:3343][p:3334][core][trace] /home/user/tg2sip/tg2sip/tg.cpp:97 TG client got response with ID 1
error {
  code = 400
  message = "Can't lock file"
}

[13:06:35.934][t:3343][p:3334][core][error] TG client authorization error
error {
  code = 400
  message = "Can't lock file"
}

**Comment by Infactum** [comment]
Have you authorized with `gen_db` app before running client?
If it is not working than you should check tdlib log files. Don't forget to enable verbose logging in `settings.ini` before.

**Comment by nik13513513** [comment]
yes, i start gen_db first. But is freezes after enter tel. number. I guess it can't connect to tg servers. Can i write mtproto proxy settings in .ini file, not socks5?

**Comment by Infactum** [comment]
Afaik public version of tdlib don't have support of mtproto, thats why you can only use socks5.

**Comment by nik13513513** [comment]
Due to this: https://github.com/tdlib/td/issues/232, support of mtproto added at 1.3.0 version, but tg2sip support only 1.2.0, right?

**Comment by Infactum** [comment]
Sure.

**Comment by nik13513513** [comment]
gen_db don't produce any logs, only td.binlog, but it is binary.

**Comment by nik13513513** [comment]
Infactum, can you update tdlib to 1.3, or i may try this?

**Comment by Infactum** [comment]
It's open source project, so you can fork it and try anything.
Updating tdlib won't solve your problem fully, because you also need to set proxy for libtgvoip (audio) if you are not planning to use p2p.
Usage of VPN or placing TG2SIP server somewhere where telegram is not blocked is preferred way.

**Comment by nik13513513** [comment]
ok, thnks!
