### ISSUE TITLE
What internal number called in Telegram

### ISSUE THREAD

**Issue by yuriikirychuk** [Infactum/tg2sip#21]
How to look from what internal number called in Telegram?

**Comment by Infactum** [comment]
Please describe your question more clearly. What type of call do you mean (SIP->TG or TG->SIP) and what information is required?

**Comment by yuriikirychuk** [comment]
Имею в виду звонки `SIP -> TG`. 

Звонок в телеграм идёт с номера шлюза `SIP -> TG`, но как можно узнать с какого внутреннего номера SIP позвонили? (например, чтоб в телеграм приходило сообщение с номером SIP с которого звонят)

**Comment by Infactum** [comment]
Такого функционала на данный момент не предусмотрено.
Каких-то серьезных технических ограничений, чтобы это реализовать, нету. В момент поступления SIP вызова вы располагаете всеми заголовками + есть подключенный клиент телеграмма, следовательно отправить сообщение можно.
