### ISSUE TITLE
Prebuild native binaries crashed links

### ISSUE THREAD

**Issue by EraLimSIM** [Infactum/tg2sip#23]
Hi there!
Prebuild native binaries links are crashed

Ubuntu 18.04 Bionic
https://ci.appveyor.com/api/projects/Infactum/tg2sip/artifacts/tg2sip_bionic.zip?branch=master&job=Environment%3A%20target_name%3DUbuntu%20Bionic%2C%20docker_tag%3Dbionic

CentOS 7
https://ci.appveyor.com/api/projects/Infactum/tg2sip/artifacts/tg2sip_centos7.zip?branch=master&job=Environment%3A%20target_name%3DCentOS%207%2C%20docker_tag%3Dcentos7

AppImage package
https://ci.appveyor.com/api/projects/Infactum/tg2sip/artifacts/tg2sip.zip?branch=master&job=Environment%3A%20target_name%3DAppImage%2C%20docker_tag%3Dcentos6

**Comment by Infactum** [comment]
It’s better to use the [Releases] page (https://github.com/Infactum/tg2sip/releases), because the CI server will not forever store assembly artifacts.
However, links are ok now.
