### ISSUE TITLE
How to get CallerId from Telegram

### ISSUE THREAD

**Issue by aizukanne** [Infactum/tg2sip#27]
Hello,

This is a wonderful solution. Is it able to forward caller info to Asterisk? I want to be able to pass User Firstname and Surname to the PBX.

Thank you

**Comment by Infactum** [comment]
Extra information about caller Telegram account is stored into `X-TG-*` SIP fields.

**Comment by hectorvent** [comment]
Here the header list:

**X-TG-ID:** Telegram User Id
**X-TG-FistName:** Optional, User first name
**X-TG-LastName:** Optional, User last name
**X-TG-Username:** Optional, User username
**X-TG-Phone:** Optional, User phone number

**Comment by mariarti** [comment]
```
[from-tg]
exten => tg,1,Set(CALLERID(num)=tg+${SIP_HEADER(read,X-TG-Phone)})
same => n,ExecIf($ ["${CALLERID(num)}"="tg +"]?Set(CALLERID(num)=tg${SIP_HEADER(read,X-TG-ID)}))
same => n,Set(CALLERID(name)=tg-${SIP_HEADER(read,X-TG-FirstName)})
same => n,Dial(SIP/200,60)
```
