### ISSUE TITLE
spdlog version incompatible

### ISSUE THREAD

**Issue by oljask** [Infactum/tg2sip#29]
I am trying to compile from source on FreeBSD.
Stuck on spdlog dependancy:

```
Could not find a configuration file for package spdlog that is compatible
  with requested version 0.17.

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/spdlog/spdlogConfig.cmake, version: 1.5.0
```

full output: https://pastebin.com/Rf9fgPSh

Is there a way to go around this?

**Comment by Infactum** [comment]
You have to build all required dependencies. This includes spdlog.
Examples of how this is done on currently supported distribs can be found [here](https://github.com/Infactum/tg2sip/tree/master/buildenv).

**Comment by oljask** [comment]
Thank you.
I just want to clarify:
Do I have to downgrade sdplog from 1.5.0 to 0.17. ?

**Comment by Infactum** [comment]
Tg2sip was not tested againist newer versions of spdlog.
It might compile fine if API is compatible but this is not guaranteed.

**Comment by oljask** [comment]
thank you
