### ISSUE TITLE
Docker не собирается

### ISSUE THREAD

**Issue by dimm71** [Infactum/tg2sip#3]
Вылетает при сборке с ошибкой 

[ 40%] Building CXX object CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/tdcore.dir/build.make:590: recipe for target 'CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o' failed
make[2]: *** [CMakeFiles/tdcore.dir/td/telegram/ContactsManager.cpp.o] Error 4
CMakeFiles/Makefile2:155: recipe for target 'CMakeFiles/tdcore.dir/all' failed
make[1]: *** [CMakeFiles/tdcore.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Infactum** [comment]
Скорее всего памяти (RAM) не хватает. Где-то 6ГБ надо при однопоточной сборке.
