### ISSUE TITLE
Is there any way to add IDs for calls by telegram ID ?

### ISSUE THREAD

**Issue by everslab** [Infactum/tg2sip#31]
for calls by telegram ID. Only known IDs allowed by telegram API.
What does it mean ?
Does this mean that the user should be in the address book?
I need  to make calls by telegram ID 
Is there any way to add IDs for calls by telegram ID ?

**Comment by Infactum** [comment]
AFAIK telegram API won't let you use ID for any communications untils you get it in some legal way (address book, message etc).

**Comment by everslab** [comment]
ok. thnx
