### ISSUE TITLE
Install td 1.6.0

### ISSUE THREAD

**Issue by wzooroo** [Infactum/tg2sip#32]
Will there be support for TD 1.6.0? Or will 1.2.0 be so?
Поддержка td 1.6.0 предвидится? Не ставится на 1.6.0(

**Comment by Infactum** [comment]
While library version upgrade is possible, its still a question what gateway function doesn't work with current one?

**Comment by wzooroo** [comment]
Everything is working. But the TD has been updated, and the installation of 1.6.0 is much faster than 1.2.0.
Все работает. Но тд обновился, да и установка 1.6.0 намного быстрей чем 1.2.0.
