### ISSUE TITLE
Compiling Instructions

### ISSUE THREAD

**Issue by gargola-dev** [Infactum/tg2sip#38]
Hello dear, 

Is there anyone who has some instructions to compile tg2sip. I am not a programer, but I can handle installing packages from source in my linux PC. 

Thank you very much!

**Comment by Infactum** [comment]
There is really good article in russian about compilation and usage [here](https://voxlink.ru/kb/asterisk-configuration/ustanovka-i-nastrojka-sip-shljuza-dlja-telegram/).

**Comment by gargola-dev** [comment]
Dear Infactum!

Thank you very much! I will read and translate, and if I may, I will get
back to you!

Thank you again!
