### ISSUE TITLE
Could you please provide an example of minimal PJSIP configuration?

### ISSUE THREAD

**Issue by grwlf** [Infactum/tg2sip#42]
Hi, I'm not an Asterisk neither a SIP expert, but still want to setup a simple voice-telegram relay. Could you please provide an example PJSIP configuration?

**Comment by grwlf** [comment]
The related issue is https://github.com/Infactum/tg2sip/issues/15. AFAIK the manual mentioned there provides the configuration for SIP Asterisk module, while I'm asking for PJSIP one.
BR

**Comment by Infactum** [comment]
I'm also not an Asterisk expert. You could try to ask help in some VoIP related telegram groups - [here ](https://t.me/ru_voip)for example.

**Comment by grwlf** [comment]
Got it, thanks. Will ask Asterisk guys.

**Comment by grwlf** [comment]
FYI https://community.asterisk.org/t/help-translating-a-simple-peer-config-to-pjsip/86601

**Comment by Infactum** [comment]
I think you should comapre INVITE SDP between pjsip and old asterisk sip config.

**Comment by grwlf** [comment]
So here is the log of the connection using older `chan_sip` of Asterisk. Unfortunately, the problem is the same `Request verification failed: Not Acceptable Here [status=170488]`, plus codec warning.

https://gist.github.com/grwlf/cd78f2581c71125fa8b026fb66bb6ae5

Also I've noticed that someone mentioned the same error in the comments to the original setup guide. Do you have any ideas? https://voxlink.ru/kb/asterisk-configuration/ustanovka-i-nastrojka-sip-shljuza-dlja-telegram/#comment-908

**Comment by grwlf** [comment]
Does tg2sip use codec directly or relies to pjsip instead?

**Comment by grwlf** [comment]
Update: So it looks like the problem was related to my PJSIP installation which had opus codec disabled. After enabling it the 'not acceptable here' problem seems gone.

**Comment by grwlf** [comment]
Finally I came to this config https://community.asterisk.org/t/help-translating-a-simple-peer-config-to-pjsip/86601/5?u=grwlf
