### ISSUE TITLE
Качество звука.

### ISSUE THREAD

**Issue by DemonUk** [Infactum/tg2sip#44]
Помогите, пожалуйста, долго пытался собрать программу для Manjaro aarch64 в итоге получилось, но проблемы со звуком. Не могу понять почему. Собирал с pjproject 2.8 (git Infactum) и 2.9, разницы нет. Суть проблемы: при исходяещем из sip в telegram, звук приходит только из sip в telegram. При входящем в sip из telegram, несколько сценариев. Первый сценарий - если звонок на прямую на внутренний номер, то звука нет вообще и через какое-то время звонок сбрасывается. При этом moh музыку в telegram клиенте, до поднятия трубки,  слышно. Второй сценарий, через IVR меню. Asterisk берет трубку включает IVR, потом звонит на внутренний номер. IVR в telegram слышно, при этом качество нормальное, при подъеме трубки, звук из sip в telegram, есть и хороший, а вот из telegram в sip есть, но очень искаженный и прерывистый так что едва можно понять речь. Помогите понять причину.
При сборке было несколько замечаний, возможно это они являются причиной.

  [6%] Building CXX object libtgvoip/CMakeFiles/libtgvoip.dir/audio/AudioIO.cpp.o
tg2sip/libtgvoip/audio/AudioIO.cpp: В статической функции-члене «static tgvoip::audio::AudioIO* tgvoip::audio::AudioIO::Create(std::string, std::string)»:
tg2sip/libtgvoip/audio/AudioIO.cpp:88:1: предупреждение: в функции, которая должна возвращать значение, отсутствует оператор return [-Wreturn-type]
   88 | }
      | ^
[ 97%] Building CXX object CMakeFiles/tg2sip.dir/tg2sip/main.cpp.o
In file included from tg2sip/tg2sip/gateway.h:24,
                 from tg2sip/tg2sip/main.cpp:27:
tg2sip/include/boost/sml.hpp:2528:8: предупреждение: неопределённая «__has_builtin»
 2528 | #undef __has_builtin
      |        ^~~~~~~~~~~~~
[ 99%] Building CXX object CMakeFiles/tg2sip.dir/tg2sip/gateway.cpp.o
In file included from tg2sip/tg2sip/gateway.h:24,
                 from tg2sip/tg2sip/gateway.cpp:19:
tg2sip/include/boost/sml.hpp:2528:8: предупреждение: неопределённая «__has_builtin»
 2528 | #undef __has_builtin
      |        ^~~~~~~~~~~~~

Заранее, спасибо за помощь.

**Comment by Infactum** [comment]
В предупреждениях при компиляции ничего критичного нету.
Если переживаете, что собрали неправильно, можно взять готовые [тут](https://github.com/Infactum/tg2sip/releases).
Причина проблем со звуком практически точно в настройках Asterisk, с которыми я помочь не могу. Могу предложить по пробовать обратиться в канал [ru_voip](https://t.me/ru_voip) в телеграме с этим вопросом.
