### ISSUE TITLE
при установке на  CentOS Linux release 7.7.1908 выходит такая ошибка

### ISSUE THREAD

**Issue by bottookku** [Infactum/tg2sip#45]
[root@localhost td]# git apply /usr/src/tdlib_header.patch
error: patch failed: td/telegram/Td.cpp:4899
error: td/telegram/Td.cpp: patch does not apply
[root@localhost td]# git apply /usr/src/tdlib_threadname.patch
You have new mail in /var/spool/mail/root
[root@localhost td]#

**Comment by Infactum** [comment]
Маловероятно, что ОС в данном случае играет какую-то роль.
Патч предназначен для конкретной версии TDLib.
Более точно можно увидеть в скриптах для CI.

**Comment by bottookku** [comment]
> Маловероятно, что ОС в данном случае играет какую-то роль.
> Патч предназначен для конкретной версии TDLib.
> Более точно можно увидеть в скриптах для CI.

знать бы где этот Cl находится

**Comment by Infactum** [comment]
https://github.com/Infactum/tg2sip/blob/6e081025593e2891b8ceeb743b140ef2733e3438/buildenv/Dockerfile.centos7#L23-L34
Используется TDLib 1.6.0
