### ISSUE TITLE
когда запускаю готовую компилированную версию для centos то получаю такую ошибку 

### ISSUE THREAD

**Issue by bottookku** [Infactum/tg2sip#46]
[00:43:10.523][t:32162][p:32162][pjsip][info] pjsua version 2.9 for Linux-3.10.4.38/x86_64/glibc-2.17 initialized
[00:43:10.537][t:32171][p:32162][core][error] TG client auto sign-on failed
[00:43:10.537][t:32162][p:32162][core][critical] failed to start TG client

**Comment by bottookku** [comment]
так и не смог компилиовать -- Found Threads: TRUE
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a configuration file for package "Td" that is compatible
  with requested version "1.6.0".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/Td/TdConfig.cmake, version: 1.2.0



-- Configuring incomplete, errors occurred!


как ранее писали в комментах, надо было определенную версию TD надо было качать

**Comment by Infactum** [comment]
Вот [тут](https://voxlink.ru/kb/asterisk-configuration/ustanovka-i-nastrojka-sip-shljuza-dlja-telegram/) есть прекрасная статья по настройке.
