### ISSUE TITLE
как нибудь кроме номера звонящего можно отправить имя звонящего если контакт ему не известен??

### ISSUE THREAD

**Issue by bottookku** [Infactum/tg2sip#48]

**Comment by bottookku** [comment]
ну например я звоню меня зовут Вася я звоню номеру у которого нет моего номера в его контактах, при этом я хочу чтобы он уивдел как меня зовут.

**Comment by alex-eri** [comment]
Callerid(name) переменную пробовал ставить?

**Comment by bottookku** [comment]
> Callerid(name) переменную пробовал ставить?

я имел ввиду не со стороны SIP а со стороны telegram.

**Comment by bottookku** [comment]
придется делать так
