### ISSUE TITLE
tdlib API level 133 required since 2022.01.01

### ISSUE THREAD

**Issue by Infactum** [Infactum/tg2sip#51]
> Уважаемый разработчик,
> 
> Популярность Telegram продолжает расти по всему миру, в том числе и благодаря Вашему неофициальному приложению. Если приложение основано на Вашем собственном коде, Вам необходимо внести два изменения, чтобы пользователи могли продолжать им пользоваться. Эти изменения уже поддержаны в открытом коде официальных приложений Telegram, так что если Ваше приложение опирается на актуальную версию одного из них, то дополнительных действий не потребуется.
> 
> Поддержка int64 для ID
> В связи с быстрым ростом Telegram переходит с 32-битных на 64-битные ID, чтобы пользователи могли и дальше создавать миллиарды новых учетных записей, групп, каналов и ботов. Необходимо как можно скорее поддержать новые ID в Вашем приложении, чтобы оно продолжило работать корректно. 
> 
> Для этого, пожалуйста, убедитесь, что приложение поддерживает 133 слой API, опубликованный в сентябре: https://core.telegram.org/api/layers#layer-133
> 
> Рекламные сообщения
> Чтобы покрывать расходы, которые увеличиваются вместе с числом пользователей, Telegram разработал рекламные сообщения (https://promote.telegram.org/) – платный инструмент для продвижения каналов и ботов с учетом заботы о конфиденциальности пользователей. Большинство сторонних разработчиков уже внедрили поддержку рекламных сообщений Telegram в свои приложения.
> 
> До 1 января 2022 мы просим Вас убедиться, что Ваше приложение поддерживает и корректно отображает рекламные сообщения. К сожалению, Telegram не сможет взять на себя расходы по поддержке приложений, в которых не отображаются рекламные сообщения, и будет вынужден отключить таким приложениям доступ к API.
> 
> Необходимая техническая документация:
> https://core.telegram.org/api/sponsored-messages
> 
> Использование Telegram API останется бесплатным для всех разработчиков. Мы будем признательны за понимание и надеемся, что Telegram и Ваше приложение смогут и дальше предоставлять людям надежный и безопасный способ связи.
> 
> Подробнее о рекламных сообщениях: https://t.me/durov_russia/35
> 
> Команда Telegram

**Comment by ionwerz** [comment]
@Infactum у вас будет возможность сделать апдейт если tdlib обновят до Нового Года до версии 1.8.0 в которой должны внести все необходимые изменения? Сейчас на данный момент версия 1.7.9 собирается с ошибками только в модуле gateway.cpp из за некоторых разбежностей в классах, все остальное компилируется нормально.

**Comment by pit941** [comment]
для тех кто использует библиотеки  уже проблемы,

**Comment by funchaser** [comment]
Need new version of tg2sip !!!

./gen_db
Enter phone number: +7…..
Error: error {
 code = 406
 message = «UPDATE_APP_TO_LOGIN»
}

**Comment by ionwerz** [comment]
Who is able to update tg2sip to lates tdlib 1.7.9 please PM me I will pay for this. 99% of code is compiling without an issue except the gateway.cpp, there is few changes that have to be aligned with a new tdlib

**Comment by TgOpss** [comment]
@ionwerz

the best we can do  - is send a donation at the bottom of the page https://github.com/Infactum/tg2sip to @Infactum to support the development of the project

I am now trying to build tg2sip with lates tdlib from master

**Comment by everslab** [comment]
> @ionwerz
> 
> the best we can do - is send a donation at the bottom of the page https://github.com/Infactum/tg2sip to @Infactum to support the development of the project
> 

\+

**Comment by TgOpss** [comment]
found a recent implementation of calls

https://github.com/ars3niy/tdlib-purple/blob/master/call.cpp

we can use it as hints

maybe someone can combine gatway.cpp with this code

I'm trying to do it now, we can try to come to something with common efforts

found more recent attempts to implement libtgvoip
https://github.com/maxoodf/tgvoip

we will do everything to make tg2sip live
#tg2sipmustlive

**Comment by TgOpss** [comment]
found a fresh implementation of tgcalls

https://github.com/TelegramMessenger/tgcalls

maybe this will help something
#tg2sipmustlive

**Comment by TgOpss** [comment]
**_hi all_**
compiled **tg2sip** with **tdlib 1.7.9**, I will try to build it under **1.7.10**

**calls work**
I wonder if it will work after 01/01/2022

[
![image](https://user-images.githubusercontent.com/95701997/145210012-2be41ae4-21a9-4d86-bb0a-aca8f22fc3b3.png)
](url)

**Comment by kaners80** [comment]
> calls work
Show me what changes have been made to gateway.cpp
Can you fork with the changes?

**Comment by dvglab** [comment]
> **_hi all_** compiled **tg2sip** with **tdlib 1.7.9**, I will try to build it under **1.7.10**
> 
> **calls work** I wonder if it will work after 01/01/2022
Pls share your fork.

**Comment by Infactum** [comment]
Waiting for a feedback on PR.
It does compile but I don't even tried to run it.

**Comment by funchaser** [comment]
./gen_db
Authorization OK

server(centos7):
./tg2sip
[12:55:29.724][t:14480][p:14471][core][info] TG client authorization ready
[12:55:29.724][t:14471][p:14471][core][info] Loading contacts cache
[12:55:29.843][t:14471][p:14471][core][info] Loaded 1 usernames and 9 phones into contacts cache
[12:55:29.850][t:14480][p:14471][core][info] TG client connected
[12:58:10.288][t:14907][p:14471][core][critical] Unhandled exception: map::at
Aborted (core dumped)

client (phone):
Exchanging encryption keys... Failed to connect

**Comment by ionwerz** [comment]
Outgoing calls (tg2sip -> telegram) do not work if we call by ID to the new type of ID which is staring from "5" for example "5028156719" this is my telegram ID which I use in official Telegram app, if I place the call by ID I get next warning `[core][warning] [6486-1] called invalid extension 5028156719`

**Comment by kaners80** [comment]
in gateway.cpp replace: 
ctx.user_id = std::stoi(ext); 
by: 
**ctx.user_id = std::stol(ext);**

**Comment by dkovik** [comment]
If I send DTMF using the chat (Telegram->SIP), it shows in the log as received, but the DTMF digits are not transmitted. With the old version DTMF works fine.
