### ISSUE TITLE
td 1.7.10

### ISSUE THREAD

**Issue by odseg** [Infactum/tg2sip#56]
pls add in description what for td 1.7.10  need "git reset --hard a53cb30e99f937cfd64e0266fa558785a184a553" because in tags of "td" not present 1.7.10
it save time for many peoples.

**Comment by Infactum** [comment]
td authors don't tag minor releases, thats why direct commit is used.
See https://github.com/tdlib/td/commit/a53cb30e99f937cfd64e0266fa558785a184a553, which refers to 1.7.10 version increment.
