### ISSUE TITLE
Problem with utils.cpp.o

### ISSUE THREAD

**Issue by ghost** [Infactum/tg2sip#59]
I trying compile the project and getting errors:

`[ 98%] Building CXX object CMakeFiles/tg2sip.dir/tg2sip/utils.cpp.o
/usr/src/tg2sip/tg2sip/utils.cpp:21:64: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
bool is_digits(const std::string &str) { return std::all_of(str.begin(), str.end(), ::isdigit); };
                                                               ^
/usr/lib/llvm-10/bin/../include/c++/v1/iosfwd:209:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/usr/src/tg2sip/tg2sip/utils.cpp:21:77: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
bool is_digits(const std::string &str) { return std::all_of(str.begin(), str.end(), ::isdigit); };
                                                                            ^
/usr/lib/llvm-10/bin/../include/c++/v1/iosfwd:209:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/usr/src/tg2sip/tg2sip/utils.cpp:21:87: error: no member named 'isdigit' in the global namespace; did you mean 'is_digits'?
bool is_digits(const std::string &str) { return std::all_of(str.begin(), str.end(), ::isdigit); };
                                                                                    ~~^~~~~~~
                                                                                      is_digits
/usr/src/tg2sip/tg2sip/utils.cpp:21:6: note: 'is_digits' declared here
bool is_digits(const std::string &str) { return std::all_of(str.begin(), str.end(), ::isdigit); };
     ^
3 errors generated.
make[2]: *** [CMakeFiles/tg2sip.dir/build.make:128: CMakeFiles/tg2sip.dir/tg2sip/utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/tg2sip.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by Infactum** [comment]
Please check you build environment: `std::isdigit` should be implemented by standard library.
See https://github.com/Infactum/tg2sip/tree/master/buildenv for details.
