### ISSUE TITLE
Решение работает?

### ISSUE THREAD

**Issue by utya** [Infactum/tg2sip#70]
Добрый день, подскажите не могу понять решение рабочие или нет. Где то читаю что какуе-то библиотеку выпилил, поэтому не работает, где то пишут что всё работает. Есть те кто ставит недавно. и у них всё работает. Звонки с телеграм клиента под ios android c переадресацией на sip?

**Comment by parasolium** [comment]
Только что поставил, проверил, на андроиде работает

**Comment by utya** [comment]
> Только что поставил, проверил, на андроиде работает

спасибо за ответ, значит решение просто у меня в докере не работало, буду поднимать на хосте. Спс.
